### ISSUE TITLE
Clang 8 bundle

### ISSUE THREAD

**Issue by brendandahl** [jyavenard/mozilla-icecream#3]
Do you have an updated bundle for clang8? For some reason my local bundles always have issues, but yours work great!

**Comment by mnoorenberghe** [comment]
@jyavenard I guess this got auto-closed because of how I mentioned it in #4 but that didn't actually include the 8.0.0 binaries. Do you plan to add them?

**Comment by jyavenard** [comment]
I no longer use icecream. I find that a 18 cores PC with sccache does wonders already :)
